'use client';

import React, { useState } from 'react';
import { ProtectedRoute } from '@/components/ProtectedRoute';
import { UserRole } from '@/types';
import BrandHeader from '@/components/BrandHeader';
import { apiService } from '@/services/api';
import { ShieldAlert, ShieldCheck, QrCode, Lock, Loader2 } from 'lucide-react';
import { toast } from 'sonner';

function SecuritySettingsContent() {
  const [loading, setLoading] = useState(false);
  const [qrCodeUrl, setQrCodeUrl] = useState<string | null>(null);
  const [verificationCode, setVerificationCode] = useState('');
  const [is2FAEnabled, setIs2FAEnabled] = useState(false); // In reality, fetch from user profile

  const generate2FA = async () => {
    setLoading(true);
    try {
      const data = await apiService.generate2FA();
      setQrCodeUrl(data.qrCodeDataUrl);
    } catch (err) {
      toast.error('Failed to generate 2FA secret');
    } finally {
      setLoading(false);
    }
  };

  const turnOn2FA = async (e: React.FormEvent) => {
    e.preventDefault();
    if (verificationCode.length !== 6) return;

    setLoading(true);
    try {
      await apiService.turnOn2FA(verificationCode);
      setIs2FAEnabled(true);
      setQrCodeUrl(null);
      setVerificationCode('');
      toast.success('Two-Factor Authentication successfully enabled!');
    } catch (err) {
      toast.error('Invalid verification code');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 pb-16">
      <BrandHeader subtitle="Security Settings" />

      <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 pt-8">
        
        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
          <div className="p-8 border-b border-gray-100">
            <div className="w-16 h-16 bg-blue-50 rounded-2xl flex items-center justify-center mb-6">
              <ShieldAlert className="w-8 h-8 text-blue-600" />
            </div>
            <h2 className="text-2xl font-bold text-gray-900 mb-2">Two-Factor Authentication (2FA)</h2>
            <p className="text-gray-500 max-w-2xl">
              Add an extra layer of security to your account. Once enabled, you'll be required to enter both your password and an authentication code from your mobile app (e.g., Google Authenticator, Authy) when signing in.
            </p>
          </div>

          <div className="p-8">
            {is2FAEnabled ? (
              <div className="bg-emerald-50 border border-emerald-200 rounded-xl p-6 flex items-start gap-4">
                <ShieldCheck className="w-8 h-8 text-emerald-600 shrink-0" />
                <div>
                  <h3 className="text-lg font-bold text-emerald-900">2FA is Enabled</h3>
                  <p className="text-emerald-800 text-sm mt-1">
                    Your account is highly secure. You will be prompted for an authenticator code during login.
                  </p>
                </div>
              </div>
            ) : !qrCodeUrl ? (
              <div className="flex flex-col items-start gap-4">
                <div className="bg-amber-50 text-amber-800 px-4 py-3 rounded-lg text-sm border border-amber-200 flex items-center gap-2 w-full max-w-md">
                  <Lock className="w-4 h-4 shrink-0" />
                  Your account is currently vulnerable.
                </div>
                <button
                  onClick={generate2FA}
                  disabled={loading}
                  className="bg-gray-900 text-white px-6 py-3 rounded-xl font-medium hover:bg-gray-800 transition flex items-center gap-2"
                >
                  {loading ? <Loader2 className="w-5 h-5 animate-spin" /> : <QrCode className="w-5 h-5" />}
                  Setup Authenticator App
                </button>
              </div>
            ) : (
              <div className="bg-gray-50 border border-gray-200 rounded-2xl p-8 max-w-xl">
                <h3 className="font-bold text-gray-900 mb-6 text-lg">Scan this QR Code</h3>
                <div className="flex items-center gap-8">
                  <div className="bg-white p-4 rounded-xl shadow-sm border border-gray-100 shrink-0">
                    <img src={qrCodeUrl} alt="2FA QR Code" className="w-40 h-40" />
                  </div>
                  <div className="flex-1">
                    <p className="text-sm text-gray-600 mb-4">
                      Scan the QR code using an authenticator app (Google Authenticator, Authy, etc.). Then, enter the 6-digit code generated by the app below.
                    </p>
                    <form onSubmit={turnOn2FA} className="space-y-4">
                      <input
                        type="text"
                        maxLength={6}
                        required
                        value={verificationCode}
                        onChange={(e) => setVerificationCode(e.target.value.replace(/\D/g, ''))}
                        placeholder="000000"
                        className="w-full text-center text-2xl tracking-[0.5em] font-mono py-3 rounded-xl border border-gray-300 focus:border-blue-500 focus:ring-1 focus:ring-blue-500 outline-none transition bg-white"
                      />
                      <button
                        type="submit"
                        disabled={loading || verificationCode.length !== 6}
                        className="w-full bg-blue-600 text-white py-3 rounded-xl font-medium hover:bg-blue-700 transition disabled:opacity-50 flex items-center justify-center gap-2"
                      >
                        {loading ? <Loader2 className="w-5 h-5 animate-spin" /> : 'Verify & Enable'}
                      </button>
                    </form>
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>

      </main>
    </div>
  );
}

export default function SecuritySettingsPage() {
  return (
    <ProtectedRoute allowedRoles={[UserRole.STUDENT, UserRole.ADMIN, UserRole.BOARDING_PROVIDER]}>
      <SecuritySettingsContent />
    </ProtectedRoute>
  );
}
